# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ap__Q22h-Gv8QPjjU9hvc7miLDpOY5J5
"""

# final_blackrock_dashboard.py

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from joblib import load
import io

# Load trained model
model = load("financial_forecast_model.joblib")

# Page setup
st.set_page_config(page_title="Private Market Forecasting App", layout="wide")
st.title("📈 Private Market Forecasting Terminal")
st.markdown("""
This app forecasts company revenue and valuation using AI-driven models, risk simulation, and investment metrics — tailored for private equity decision-making.
""")

# Sidebar inputs
st.sidebar.header("🔢 Input Financial Metrics")
revenue_input = st.sidebar.slider("Current Revenue (in millions)", 10.0, 500.0, 99.97)
profit_margin = st.sidebar.slider("Profit Margin (%)", 1.0, 50.0, 10.0)
debt_equity = st.sidebar.slider("Debt to Equity Ratio", 0.0, 5.0, 1.5)
cash_flow = st.sidebar.slider("Cash Flow (in millions)", 0.0, 500.0, 40.0)

# Predict future revenue using ML model
input_df = pd.DataFrame({
    "Revenue": [revenue_input],
    "ProfitMargin": [profit_margin],
    "DebtEquity": [debt_equity],
    "CashFlow": [cash_flow]
})

predicted_revenue = model.predict(input_df)[0]
valuation = predicted_revenue * 5  # example 5x multiple

# Value-at-Risk calculation (95% confidence)
var = predicted_revenue - 1.65 * np.std([revenue_input, predicted_revenue])

# Monte Carlo simulation for valuation
simulations = 1000
results = []
for _ in range(simulations):
    rev_sim = np.random.normal(predicted_revenue, predicted_revenue * 0.1)
    val_sim = rev_sim * 5
    results.append(val_sim)

# DCF calculation (simplified)
discount_rate = 0.12
years = 5
future_cashflows = [cash_flow * (1 + 0.1)**i for i in range(1, years+1)]
dcf_value = sum(cf / (1 + discount_rate)**i for i, cf in enumerate(future_cashflows, 1))

# Layout columns
col1, col2, col3 = st.columns(3)
col1.metric("Predicted Revenue (mil)", f"${predicted_revenue:.2f}")
col2.metric("Estimated Valuation (5x)", f"${valuation:.2f}")
col3.metric("Value-at-Risk (95%)", f"${var:.2f}", delta=f"-{predicted_revenue - var:.2f:.2f}")

# 📉 Monte Carlo distribution
st.subheader("📊 Monte Carlo Simulation – Valuation Distribution")
st.bar_chart(pd.Series(results))

# 📉 DCF Estimate
st.subheader("📈 Discounted Cash Flow (DCF) Estimate")
st.write(f"Total DCF Value: ${dcf_value:.2f} (over {years} years @ {discount_rate*100:.1f}% discount rate)")

# 📈 Simulated Momentum Indicators
st.subheader("📉 Momentum Indicators (Simulated EMA & MACD)")
time_index = np.arange(1, 61)
simulated_revenue_series = revenue_input * (1 + 0.01 * np.random.randn(60)).cumprod()
revenue_df = pd.DataFrame({"Time": time_index, "Revenue": simulated_revenue_series})
revenue_df.set_index("Time", inplace=True)

# Calculate EMAs
revenue_df["EMA20"] = revenue_df["Revenue"].ewm(span=20, adjust=False).mean()
revenue_df["EMA200"] = revenue_df["Revenue"].ewm(span=200, adjust=False).mean()

# MACD
ema12 = revenue_df["Revenue"].ewm(span=12, adjust=False).mean()
ema26 = revenue_df["Revenue"].ewm(span=26, adjust=False).mean()
macd = ema12 - ema26
signal = macd.ewm(span=9, adjust=False).mean()
histogram = macd - signal

# Plot revenue + EMAs
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(revenue_df.index, revenue_df["Revenue"], label="Revenue", linewidth=2)
ax.plot(revenue_df.index, revenue_df["EMA20"], label="EMA-20", linestyle="--")
ax.plot(revenue_df.index, revenue_df["EMA200"], label="EMA-200", linestyle=":")
ax.set_title("Simulated Revenue vs EMA-20 & EMA-200")
ax.legend()
st.pyplot(fig)

# Plot MACD histogram
fig2, ax2 = plt.subplots(figsize=(10, 3))
ax2.bar(revenue_df.index, histogram, label="MACD Histogram")
ax2.plot(revenue_df.index, macd, label="MACD Line", color="orange")
ax2.plot(revenue_df.index, signal, label="Signal Line", color="red")
ax2.set_title("MACD Style Momentum (Simulated)")
ax2.legend()
st.pyplot(fig2)

# 📄 Downloadable summary
st.subheader("📄 Download Forecast Report")
report = f"""
Company Forecast Summary:\n
Predicted Revenue: ${predicted_revenue:.2f}M
Estimated Valuation (5x): ${valuation:.2f}M
Value-at-Risk (95%): ${var:.2f}M
Discounted Cash Flow Value: ${dcf_value:.2f}M

Momentum Analysis:
Simulated EMA & MACD indicate growth trend strength.
This approach adapts public-market indicators to private company metrics for timing and benchmarking.

Generated using Private Market Forecasting App (Lakshya Chaudhary – 2025)
"""
buffer = io.BytesIO()
buffer.write(report.encode())
buffer.seek(0)
st.download_button("📥 Download Summary Report", data=buffer, file_name="forecast_summary.txt")